#!/usr/bin/env python3
"""Extended independent certificates for the multi-block QGN addendum v3.

This suite checks the joint Lie algebra, the complete charge-sector kernel
formula, the fixed-composition MB3 criterion, and the determinant-resonance
parity rule.  It includes the four v2 cases and two adversarial additions:

  * L=(1,2) with an odd-capacity resonance.  Every even sector is exactly the
    product-AGP span, while the three-particle sector contains two determinant
    dark states.
  * L=(1,2,2) with a synchronized pair of L=2 blocks and simultaneous even-
    and odd-capacity center resonances.  The theorem's charge-sector formula
    is compared against exact diagonalization in every sector N=0,...,10.

Only NumPy is required.
"""

from __future__ import annotations

import itertools
import math
from collections import defaultdict, deque
from dataclasses import dataclass
from typing import Callable, Iterable, Sequence

import numpy as np

TOL = 1.0e-10


# ---------------------------------------------------------------------------
# One-body frames and linear closures
# ---------------------------------------------------------------------------


def two_basis_frame(theta: float, first_weight: float, second_weight: float):
    """Two weighted orthonormal bases in C^2."""
    e1 = np.array([1.0, 0.0], dtype=complex)
    e2 = np.array([0.0, 1.0], dtype=complex)
    f1 = np.array([math.cos(theta), math.sin(theta)], dtype=complex)
    f2 = np.array([-math.sin(theta), math.cos(theta)], dtype=complex)
    vectors = [
        math.sqrt(first_weight) * e1,
        math.sqrt(first_weight) * e2,
        math.sqrt(second_weight) * f1,
        math.sqrt(second_weight) * f2,
    ]
    return vectors, [np.outer(v, v.conj()) for v in vectors]


def frame_graph_connected(vectors: Sequence[np.ndarray], tol: float = TOL) -> bool:
    active = [i for i, v in enumerate(vectors) if np.vdot(v, v).real > tol]
    if not active:
        return False
    adjacency = {i: [] for i in active}
    for i, j in itertools.combinations(active, 2):
        if abs(np.vdot(vectors[i], vectors[j])) > tol:
            adjacency[i].append(j)
            adjacency[j].append(i)
    seen = {active[0]}
    queue = deque([active[0]])
    while queue:
        i = queue.popleft()
        for j in adjacency[i]:
            if j not in seen:
                seen.add(j)
                queue.append(j)
    return len(seen) == len(active)


def real_vector(matrix: np.ndarray) -> np.ndarray:
    return np.concatenate((matrix.real.ravel(), matrix.imag.ravel()))


def add_if_independent(
    basis: list[np.ndarray], candidate: np.ndarray, *, real: bool, tol: float = TOL
) -> bool:
    vector = real_vector(candidate) if real else candidate.ravel()
    if not basis:
        basis.append(candidate)
        return True
    columns = [real_vector(item) if real else item.ravel() for item in basis]
    design = np.column_stack(columns)
    coefficients, *_ = np.linalg.lstsq(design, vector, rcond=None)
    residual = np.linalg.norm(vector - design @ coefficients)
    if residual > tol:
        basis.append(candidate)
        return True
    return False


def span_residual(basis: Sequence[np.ndarray], target: np.ndarray, *, real: bool) -> float:
    if not basis:
        return float(np.linalg.norm(target))
    vector = real_vector(target) if real else target.ravel()
    design = np.column_stack(
        [real_vector(item) if real else item.ravel() for item in basis]
    )
    coefficients, *_ = np.linalg.lstsq(design, vector, rcond=None)
    return float(np.linalg.norm(vector - design @ coefficients))


def associative_closure(generators: Sequence[np.ndarray]) -> list[np.ndarray]:
    """Complex linear span of the unital algebra generated by matrices."""
    dimension = generators[0].shape[0]
    basis: list[np.ndarray] = []
    add_if_independent(basis, np.eye(dimension, dtype=complex), real=False)
    for generator in generators:
        add_if_independent(basis, generator, real=False)
    changed = True
    while changed:
        changed = False
        snapshot = list(basis)
        for left in snapshot:
            for right in generators:
                changed |= add_if_independent(basis, left @ right, real=False)
                changed |= add_if_independent(basis, right @ left, real=False)
    return basis


def lie_closure(generators: Sequence[np.ndarray]) -> list[np.ndarray]:
    """Real Lie algebra generated by skew-Hermitian matrices."""
    basis: list[np.ndarray] = []
    for generator in generators:
        add_if_independent(basis, generator, real=True)
    changed = True
    while changed:
        changed = False
        snapshot = list(basis)
        for index, left in enumerate(snapshot):
            for right in snapshot[index + 1 :]:
                changed |= add_if_independent(
                    basis, left @ right - right @ left, real=True
                )
    return basis


def block_diag(blocks: Sequence[np.ndarray]) -> np.ndarray:
    size = sum(block.shape[0] for block in blocks)
    out = np.zeros((size, size), dtype=complex)
    start = 0
    for block in blocks:
        stop = start + block.shape[0]
        out[start:stop, start:stop] = block
        start = stop
    return out


def block_generators(projectors_by_block: Sequence[Sequence[np.ndarray]]) -> list[np.ndarray]:
    number_labels = len(projectors_by_block[0])
    assert all(len(block) == number_labels for block in projectors_by_block)
    return [
        block_diag([projectors_by_block[a][lam] for a in range(len(projectors_by_block))])
        for lam in range(number_labels)
    ]


def trace_profile(projectors_by_block: Sequence[Sequence[np.ndarray]]) -> np.ndarray:
    dims = [block[0].shape[0] for block in projectors_by_block]
    number_labels = len(projectors_by_block[0])
    return np.array(
        [
            [
                np.trace(projectors_by_block[a][lam]).real / dims[a]
                for a in range(len(dims))
            ]
            for lam in range(number_labels)
        ],
        dtype=float,
    )


def gram_mismatch(
    projectors_a: Sequence[np.ndarray], projectors_b: Sequence[np.ndarray]
) -> float:
    gram_a = np.array(
        [[np.trace(x @ y).real for y in projectors_a] for x in projectors_a]
    )
    gram_b = np.array(
        [[np.trace(x @ y).real for y in projectors_b] for x in projectors_b]
    )
    return float(np.max(np.abs(gram_a - gram_b)))


# ---------------------------------------------------------------------------
# Exact fermionic construction
# ---------------------------------------------------------------------------


def fermion_basis(number_orbitals: int, number_particles: int) -> list[int]:
    return [
        sum(1 << orbital for orbital in occupied)
        for occupied in itertools.combinations(range(number_orbitals), number_particles)
    ]


def annihilate(mask: int, orbital: int):
    if not ((mask >> orbital) & 1):
        return None
    sign = -1 if (mask & ((1 << orbital) - 1)).bit_count() % 2 else 1
    return sign, mask ^ (1 << orbital)


def create(mask: int, orbital: int):
    if (mask >> orbital) & 1:
        return None
    sign = -1 if (mask & ((1 << orbital) - 1)).bit_count() % 2 else 1
    return sign, mask ^ (1 << orbital)


def second_quantize(one_body: np.ndarray, number_particles: int):
    number_orbitals = one_body.shape[0]
    basis = fermion_basis(number_orbitals, number_particles)
    index = {mask: position for position, mask in enumerate(basis)}
    operator = np.zeros((len(basis), len(basis)), dtype=complex)
    for column, mask in enumerate(basis):
        for source in range(number_orbitals):
            removed = annihilate(mask, source)
            if removed is None:
                continue
            sign_a, intermediate = removed
            for target in range(number_orbitals):
                amplitude = one_body[target, source]
                if abs(amplitude) <= 1.0e-15:
                    continue
                inserted = create(intermediate, target)
                if inserted is None:
                    continue
                sign_c, final = inserted
                operator[index[final], column] += sign_a * sign_c * amplitude
    return operator, basis


def qgn_hamiltonian(one_spin_generators: Sequence[np.ndarray], number_particles: int):
    one_spin_dimension = one_spin_generators[0].shape[0]
    factor_matrices = []
    basis = None
    for one_spin in one_spin_generators:
        signed = np.zeros((2 * one_spin_dimension, 2 * one_spin_dimension), dtype=complex)
        signed[:one_spin_dimension, :one_spin_dimension] = one_spin
        signed[one_spin_dimension:, one_spin_dimension:] = -one_spin.conj()
        factor, basis = second_quantize(signed, number_particles)
        factor_matrices.append(factor)
    hamiltonian = sum(factor.conj().T @ factor for factor in factor_matrices) / 2.0
    return hamiltonian, basis


def nullity(matrix: np.ndarray, tol: float = TOL) -> int:
    if matrix.size == 0:
        return 0
    eigenvalues = np.linalg.eigvalsh(matrix)
    return int(np.count_nonzero(eigenvalues < tol))


def charge_tuple(mask: int, block_dims: Sequence[int]) -> tuple[int, ...]:
    one_spin_dimension = sum(block_dims)
    groups: list[range] = []
    start = 0
    for dim in block_dims:
        groups.append(range(start, start + dim))
        start += dim
    start = one_spin_dimension
    for dim in block_dims:
        groups.append(range(start, start + dim))
        start += dim
    return tuple(sum((mask >> orbital) & 1 for orbital in group) for group in groups)


def charge_sector_nullities(
    hamiltonian: np.ndarray, basis: Sequence[int], block_dims: Sequence[int]
) -> dict[tuple[int, ...], int]:
    sectors: dict[tuple[int, ...], list[int]] = defaultdict(list)
    for index, mask in enumerate(basis):
        sectors[charge_tuple(mask, block_dims)].append(index)
    output: dict[tuple[int, ...], int] = {}
    for sector, indices in sectors.items():
        restricted = hamiltonian[np.ix_(indices, indices)]
        sector_nullity = nullity(restricted)
        if sector_nullity:
            output[sector] = sector_nullity
    return output


# ---------------------------------------------------------------------------
# Theorem 4.3 prediction for the certificate models
# ---------------------------------------------------------------------------


def su2_tensor_multiplicities(occupations: Sequence[int]) -> dict[int, int]:
    """SU(2) multiplicities for products of Lambda^r C^2.

    Keys are twice the spin.  Lambda^0 and Lambda^2 are trivial; Lambda^1 is
    spin 1/2.  The routine is intentionally independent of the ED code.
    """
    multiplicities = {0: 1}
    for occupation in occupations:
        if occupation in (0, 2):
            factor = {0: 1}
        elif occupation == 1:
            factor = {1: 1}
        else:
            raise ValueError(f"invalid C^2 exterior power {occupation}")
        updated: dict[int, int] = defaultdict(int)
        for j1, m1 in multiplicities.items():
            for j2, m2 in factor.items():
                for j in range(abs(j1 - j2), j1 + j2 + 1, 2):
                    updated[j] += m1 * m2
        multiplicities = dict(updated)
    return multiplicities


def predicted_sector_nullity(
    sector: tuple[int, ...],
    block_dims: Sequence[int],
    profile: np.ndarray,
    synchronization_classes: Sequence[Sequence[int]],
    tol: float = TOL,
) -> int:
    q = len(block_dims)
    r = np.array(sector[:q], dtype=int)
    s = np.array(sector[q:], dtype=int)
    delta = r - s
    if np.linalg.norm(profile @ delta, ord=np.inf) > tol:
        return 0

    answer = 1
    for cls in synchronization_classes:
        dims = {block_dims[a] for a in cls}
        if len(dims) != 1:
            raise ValueError("synchronization classes must have one common dimension")
        L = dims.pop()
        if L == 1:
            # su(1) is trivial; one-dimensional blocks are controlled only by
            # the center condition above.
            factor = 1
        elif len(cls) == 1:
            a = cls[0]
            factor = int(r[a] == s[a] or {int(r[a]), int(s[a])} == {0, L})
        elif L == 2:
            mr = su2_tensor_multiplicities([int(r[a]) for a in cls])
            ms = su2_tensor_multiplicities([int(s[a]) for a in cls])
            factor = sum(mr.get(j, 0) * ms.get(j, 0) for j in set(mr) | set(ms))
        else:
            raise NotImplementedError(
                "the extended certificate only needs multi-block synchronization at L=2"
            )
        answer *= factor
        if answer == 0:
            break
    return answer


def compare_every_charge_sector(
    name: str,
    generators: Sequence[np.ndarray],
    block_dims: Sequence[int],
    profile: np.ndarray,
    synchronization_classes: Sequence[Sequence[int]],
) -> list[int]:
    total_modes = 2 * sum(block_dims)
    totals: list[int] = []
    for number_particles in range(total_modes + 1):
        hamiltonian, basis = qgn_hamiltonian(generators, number_particles)
        observed = charge_sector_nullities(hamiltonian, basis, block_dims)

        predicted: dict[tuple[int, ...], int] = {}
        q = len(block_dims)
        for r in itertools.product(*(range(L + 1) for L in block_dims)):
            for s in itertools.product(*(range(L + 1) for L in block_dims)):
                if sum(r) + sum(s) != number_particles:
                    continue
                sector = tuple(r + s)
                value = predicted_sector_nullity(
                    sector, block_dims, profile, synchronization_classes
                )
                if value:
                    predicted[sector] = value

        if observed != predicted:
            all_keys = sorted(set(observed) | set(predicted))
            details = [
                (key, observed.get(key, 0), predicted.get(key, 0))
                for key in all_keys
                if observed.get(key, 0) != predicted.get(key, 0)
            ]
            raise AssertionError(
                f"{name}: charge-sector mismatch at N={number_particles}: {details}"
            )
        totals.append(sum(observed.values()))
    return totals


# ---------------------------------------------------------------------------
# Model builders
# ---------------------------------------------------------------------------


def scalar_block(weights: Sequence[float]):
    vectors = [np.array([math.sqrt(weight)], dtype=complex) for weight in weights]
    projectors = [np.array([[weight]], dtype=complex) for weight in weights]
    return vectors, projectors


def unequal_capacity_frames():
    """Connected tight frames in C^2 and C^3 with identical normalized traces."""
    vectors_two = []
    for theta in (0.0, math.pi / 4.0, math.pi / 8.0):
        vectors_two.extend(
            [
                np.array([math.cos(theta), math.sin(theta)], dtype=complex),
                np.array([-math.sin(theta), math.cos(theta)], dtype=complex),
            ]
        )
    vectors_two = [math.sqrt(1.0 / 3.0) * vector for vector in vectors_two]

    standard = np.eye(3, dtype=complex)
    omega = np.exp(2j * math.pi / 3.0)
    fourier = np.array(
        [[omega ** (row * column) for column in range(3)] for row in range(3)],
        dtype=complex,
    ) / math.sqrt(3.0)
    vectors_three = [standard[:, column] for column in range(3)]
    vectors_three.extend(fourier[:, column] for column in range(3))
    vectors_three = [math.sqrt(1.0 / 2.0) * vector for vector in vectors_three]

    return (
        vectors_two,
        [np.outer(v, v.conj()) for v in vectors_two],
        vectors_three,
        [np.outer(v, v.conj()) for v in vectors_three],
    )


@dataclass
class Model:
    name: str
    block_dims: tuple[int, ...]
    vectors_by_block: tuple[tuple[np.ndarray, ...], ...]
    projectors_by_block: tuple[tuple[np.ndarray, ...], ...]
    synchronization_classes: tuple[tuple[int, ...], ...]

    @property
    def generators(self) -> list[np.ndarray]:
        return block_generators(self.projectors_by_block)

    @property
    def profile(self) -> np.ndarray:
        return trace_profile(self.projectors_by_block)


def make_two_block_model(
    name: str,
    theta_a: float,
    theta_b: float,
    weights_a: tuple[float, float],
    weights_b: tuple[float, float],
    synchronized: bool = False,
) -> Model:
    vectors_a, projectors_a = two_basis_frame(theta_a, *weights_a)
    vectors_b, projectors_b = two_basis_frame(theta_b, *weights_b)
    classes = ((0, 1),) if synchronized else ((0,), (1,))
    return Model(
        name,
        (2, 2),
        (tuple(vectors_a), tuple(vectors_b)),
        (tuple(projectors_a), tuple(projectors_b)),
        classes,
    )


def make_odd_resonance_model() -> Model:
    vectors_a, projectors_a = scalar_block([0.5, 0.5, 0.5, 0.5])
    vectors_b, projectors_b = two_basis_frame(math.pi / 4.0, 0.5, 0.5)
    return Model(
        "Odd-F resonance: L=(1,2), Z=span(2,1)",
        (1, 2),
        (tuple(vectors_a), tuple(vectors_b)),
        (tuple(projectors_a), tuple(projectors_b)),
        ((0,), (1,)),
    )


def make_mixed_mechanism_model() -> Model:
    vectors_a, projectors_a = scalar_block([0.5, 0.5, 0.5, 0.5])
    vectors_b, projectors_b = two_basis_frame(math.pi / 4.0, 0.5, 0.5)
    # C is label-by-label identical to B, hence synchronized.
    vectors_c = [v.copy() for v in vectors_b]
    projectors_c = [p.copy() for p in projectors_b]
    return Model(
        "Mixed mechanisms: L=(1,2,2), synchronized {B,C}, Z=span(2,1,1)",
        (1, 2, 2),
        (tuple(vectors_a), tuple(vectors_b), tuple(vectors_c)),
        (tuple(projectors_a), tuple(projectors_b), tuple(projectors_c)),
        ((0,), (1, 2)),
    )


# ---------------------------------------------------------------------------
# Reporting and tests
# ---------------------------------------------------------------------------


def print_model_summary(model: Model) -> tuple[int, int, int]:
    generators = model.generators
    associative = associative_closure(generators)
    lie = lie_closure([1j * generator for generator in generators])
    rank = int(np.linalg.matrix_rank(model.profile, tol=TOL))

    print(f"\n{model.name}")
    print("-" * len(model.name))
    for a, (vectors, projectors, dim) in enumerate(
        zip(model.vectors_by_block, model.projectors_by_block, model.block_dims, strict=True)
    ):
        tight = sum(projectors)
        c = np.trace(tight).real / dim
        print(f"Block {a}: dim={dim}, tight error={np.linalg.norm(tight-c*np.eye(dim)):.3e}, "
              f"connected={frame_graph_connected(vectors)}")
    print("Trace profile:\n", model.profile)
    print("Trace-profile rank:", rank)
    print("Complex associative dimension:", len(associative))
    print("Real Lie dimension:", len(lie))
    return len(associative), len(lie), rank


def check_counterexample_center_membership(model: Model) -> None:
    lie = lie_closure([1j * generator for generator in model.generators])
    total_center = 1j * block_diag([np.eye(2), np.eye(2)])
    relative_center = 1j * block_diag([np.eye(2), -np.eye(2)])
    total_residual = span_residual(lie, total_center, real=True)
    relative_residual = span_residual(lie, relative_center, real=True)
    print("Total-center membership residual:", f"{total_residual:.3e}")
    print("Relative-center membership residual:", f"{relative_residual:.3e}")
    assert total_residual < 1.0e-9
    assert relative_residual > 1.0e-3

    # Explicit determinant dark states.  Ordering is
    # A-up(0,1), B-up(2,3), A-down(4,5), B-down(6,7).
    number_particles = 4
    masks = [
        (1 << 0) | (1 << 1) | (1 << 6) | (1 << 7),
        (1 << 2) | (1 << 3) | (1 << 4) | (1 << 5),
    ]
    max_residual = 0.0
    for generator in model.generators:
        signed = np.zeros((8, 8), dtype=complex)
        signed[:4, :4] = generator
        signed[4:, 4:] = -generator.conj()
        factor, basis = second_quantize(signed, number_particles)
        index = {mask: position for position, mask in enumerate(basis)}
        for mask in masks:
            state = np.zeros(len(basis), dtype=complex)
            state[index[mask]] = 1.0
            max_residual = max(max_residual, float(np.linalg.norm(factor @ state)))
    print("Explicit determinant-state factor residual:", f"{max_residual:.3e}")
    assert max_residual < 1.0e-12


def total_nullities(model: Model) -> list[int]:
    totals = []
    for number_particles in range(2 * sum(model.block_dims) + 1):
        hamiltonian, _ = qgn_hamiltonian(model.generators, number_particles)
        totals.append(nullity(hamiltonian))
    return totals


def main() -> None:
    counterexample = make_two_block_model(
        "Counterexample: full *-algebra but missing relative center",
        theta_a=math.pi / 4.0,
        theta_b=math.pi / 6.0,
        weights_a=(0.5, 0.5),
        weights_b=(0.5, 0.5),
    )
    assoc, lie_dim, trace_rank = print_model_summary(counterexample)
    assert gram_mismatch(
        counterexample.projectors_by_block[0], counterexample.projectors_by_block[1]
    ) > 1.0e-3
    assert (assoc, lie_dim, trace_rank) == (8, 7, 1)
    check_counterexample_center_membership(counterexample)
    totals = compare_every_charge_sector(
        counterexample.name,
        counterexample.generators,
        counterexample.block_dims,
        counterexample.profile,
        counterexample.synchronization_classes,
    )
    print("All-sector nullities N=0,...,8:", totals)
    assert totals == [1, 0, 2, 0, 5, 0, 2, 0, 1]

    repaired = make_two_block_model(
        "Repaired model: full trace rank and exact product-AGP manifold",
        theta_a=math.pi / 4.0,
        theta_b=math.pi / 6.0,
        weights_a=(1.0 / 3.0, 2.0 / 3.0),
        weights_b=(2.0 / 3.0, 1.0 / 3.0),
    )
    assoc, lie_dim, trace_rank = print_model_summary(repaired)
    assert (assoc, lie_dim, trace_rank) == (8, 8, 2)
    totals = compare_every_charge_sector(
        repaired.name,
        repaired.generators,
        repaired.block_dims,
        repaired.profile,
        repaired.synchronization_classes,
    )
    print("All-sector nullities N=0,...,8:", totals)
    assert totals == [1, 0, 2, 0, 3, 0, 2, 0, 1]

    synchronized = make_two_block_model(
        "Synchronized control",
        theta_a=math.pi / 4.0,
        theta_b=math.pi / 4.0,
        weights_a=(0.5, 0.5),
        weights_b=(0.5, 0.5),
        synchronized=True,
    )
    assoc, lie_dim, trace_rank = print_model_summary(synchronized)
    assert gram_mismatch(
        synchronized.projectors_by_block[0], synchronized.projectors_by_block[1]
    ) < TOL
    assert (assoc, lie_dim, trace_rank) == (4, 4, 1)
    totals = compare_every_charge_sector(
        synchronized.name,
        synchronized.generators,
        synchronized.block_dims,
        synchronized.profile,
        synchronized.synchronization_classes,
    )
    print("All-sector nullities N=0,...,8:", totals)
    assert totals == [1, 0, 4, 0, 10, 0, 4, 0, 1]

    vectors_two, projectors_two, vectors_three, projectors_three = unequal_capacity_frames()
    unequal = Model(
        "Unequal capacities: center deficit without determinant resonance",
        (2, 3),
        (tuple(vectors_two), tuple(vectors_three)),
        (tuple(projectors_two), tuple(projectors_three)),
        ((0,), (1,)),
    )
    assoc, lie_dim, trace_rank = print_model_summary(unequal)
    assert (assoc, lie_dim, trace_rank) == (13, 12, 1)
    totals = compare_every_charge_sector(
        unequal.name,
        unequal.generators,
        unequal.block_dims,
        unequal.profile,
        unequal.synchronization_classes,
    )
    print("All-sector nullities N=0,...,10:", totals)
    assert totals == [1, 0, 2, 0, 3, 0, 3, 0, 2, 0, 1]

    odd = make_odd_resonance_model()
    assoc, lie_dim, trace_rank = print_model_summary(odd)
    assert (assoc, lie_dim, trace_rank) == (5, 4, 1)
    totals = compare_every_charge_sector(
        odd.name,
        odd.generators,
        odd.block_dims,
        odd.profile,
        odd.synchronization_classes,
    )
    print("All-sector nullities N=0,...,6:", totals)
    assert totals == [1, 0, 2, 2, 2, 0, 1]
    # The two N=3 states are the opposite determinant resonances
    # delta=(1,-2) and delta=(-1,2).

    mixed = make_mixed_mechanism_model()
    assoc, lie_dim, trace_rank = print_model_summary(mixed)
    assert (assoc, lie_dim, trace_rank) == (5, 4, 1)
    totals = compare_every_charge_sector(
        mixed.name,
        mixed.generators,
        mixed.block_dims,
        mixed.profile,
        mixed.synchronization_classes,
    )
    print("All-sector nullities N=0,...,10:", totals)
    assert totals == [1, 0, 5, 6, 14, 8, 14, 6, 5, 0, 1]

    print("\nPASS: all six multi-block connectivity and kernel certificates reproduced.")


if __name__ == "__main__":
    main()
