#!/usr/bin/env python3
"""H4 connectivity/primitivity certificate for projected PSD-Hubbard QGN models.

This script independently checks the algebraic criterion proved in the accompanying
memo:

  * projected-orbital frame overlap graph connected
      => dynamical Lie algebra generated by the rank-one density matrices is u(L)
      => the AGP is the unique zero mode in every fixed-pair sector.

It also checks the exact disconnected-kernel counting formula and audits the
Gao-Han-Khalaf Model-I / Model-II frame graphs on a range of finite tori.

The code uses only finite-dimensional linear algebra.  It is a certificate/test,
not a substitute for the proof.
"""
from __future__ import annotations

import csv
import itertools
import json
import math
from collections import deque
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np
from numpy.typing import NDArray
from scipy.linalg import eigvalsh

Array = NDArray[np.complex128]
ROOT = Path(__file__).resolve().parent


def combinations_masks(L: int, n: int) -> tuple[int, ...]:
    return tuple(sum(1 << i for i in comb) for comb in itertools.combinations(range(L), n))


def exterior_bilinear(L: int, n: int, a: Array) -> Array:
    """Matrix of dGamma_n(a) on Lambda^n C^L in the occupation basis."""
    basis = combinations_masks(L, n)
    index = {m: i for i, m in enumerate(basis)}
    out = np.zeros((len(basis), len(basis)), dtype=np.complex128)
    for q in range(L):
        for p in range(L):
            coeff = a[p, q]
            if abs(coeff) < 1e-15:
                continue
            for col, mask in enumerate(basis):
                if not ((mask >> q) & 1):
                    continue
                # annihilate q
                sign = -1 if (mask & ((1 << q) - 1)).bit_count() % 2 else 1
                ma = mask ^ (1 << q)
                if (ma >> p) & 1:
                    continue
                # create p
                if (ma & ((1 << p) - 1)).bit_count() % 2:
                    sign *= -1
                row = index[ma | (1 << p)]
                out[row, col] += sign * coeff
    return (out + out.conj().T) / 2 if np.allclose(a, a.conj().T) else out


def commutator_hamiltonian(projectors: Sequence[Array], n: int) -> Array:
    """H = 1/2 sum_x ad_{dGamma(p_x)}^dagger ad_{dGamma(p_x)} on End(Lambda^n)."""
    L = projectors[0].shape[0]
    d = math.comb(L, n)
    ident = np.eye(d, dtype=np.complex128)
    H = np.zeros((d * d, d * d), dtype=np.complex128)
    for p in projectors:
        A = exterior_bilinear(L, n, p)
        # vec convention: vec(A T - T A) = (I kron A - A^T kron I) vec(T)
        S = np.kron(ident, A) - np.kron(A.T, ident)
        H += 0.5 * (S.conj().T @ S)
    return (H + H.conj().T) / 2


def frame_components(vectors: Sequence[Array], tol: float = 1e-11) -> list[list[int]]:
    m = len(vectors)
    adj = [[] for _ in range(m)]
    for i in range(m):
        for j in range(i + 1, m):
            if abs(np.vdot(vectors[i], vectors[j])) > tol:
                adj[i].append(j)
                adj[j].append(i)
    seen = [False] * m
    comps: list[list[int]] = []
    for i in range(m):
        if seen[i] or np.linalg.norm(vectors[i]) <= tol:
            continue
        seen[i] = True
        q = [i]
        comp = []
        while q:
            z = q.pop()
            comp.append(z)
            for w in adj[z]:
                if not seen[w]:
                    seen[w] = True
                    q.append(w)
        comps.append(comp)
    return comps


def component_dimensions(vectors: Sequence[Array], comps: Sequence[Sequence[int]], tol: float = 1e-10) -> list[int]:
    dims = []
    for comp in comps:
        M = np.column_stack([vectors[i] for i in comp])
        dims.append(int(np.linalg.matrix_rank(M, tol=tol)))
    return dims


def predicted_kernel_dim(component_dims: Sequence[int], n: int) -> int:
    # coefficient of z^n in prod_r (1+z+...+z^{L_r})
    coeff = [1]
    for d in component_dims:
        nxt = [0] * (len(coeff) + d)
        for i, a in enumerate(coeff):
            for j in range(d + 1):
                nxt[i + j] += a
        coeff = nxt
    return coeff[n] if n < len(coeff) else 0


def random_parseval_frame(L: int, m: int, rng: np.random.Generator) -> list[Array]:
    """Rows of an m x L Haar isometry, regarded as frame vectors in C^L."""
    z = rng.normal(size=(m, L)) + 1j * rng.normal(size=(m, L))
    q, _ = np.linalg.qr(z)
    # q has orthonormal columns, so sum_x |v_x><v_x| = I
    return [np.conjugate(q[x, :]) for x in range(m)]


def disconnected_parseval_frame(block_dims: Sequence[int], extra_per_block: int, rng: np.random.Generator) -> list[Array]:
    L = sum(block_dims)
    out: list[Array] = []
    offset = 0
    for d in block_dims:
        local = random_parseval_frame(d, d + extra_per_block, rng)
        for v in local:
            w = np.zeros(L, dtype=np.complex128)
            w[offset:offset + d] = v
            out.append(w)
        offset += d
    return out


def projectors_from_frame(vectors: Sequence[Array]) -> list[Array]:
    return [np.outer(v, np.conjugate(v)) for v in vectors if np.linalg.norm(v) > 1e-13]


def zero_count_and_gap(H: Array, tol: float = 2e-9) -> tuple[int, float]:
    vals = eigvalsh(H)
    zero = int(np.sum(np.abs(vals) < tol))
    positive = vals[vals >= tol]
    gap = float(positive[0]) if len(positive) else float('nan')
    return zero, gap


def lie_closure_dimension(hermitians: Sequence[Array], tol: float = 2e-10) -> int:
    """Real dimension of the skew-Hermitian Lie algebra generated by i*hermitians."""
    L = hermitians[0].shape[0]

    def realvec(X: Array) -> NDArray[np.float64]:
        return np.concatenate((X.real.ravel(), X.imag.ravel()))

    basis: list[Array] = []
    Q: list[NDArray[np.float64]] = []

    def add(X: Array) -> bool:
        X = (X - X.conj().T) / 2
        v = realvec(X)
        for q in Q:
            v = v - np.dot(q, v) * q
        norm = np.linalg.norm(v)
        if norm <= tol:
            return False
        q = v / norm
        # Store the orthogonalized matrix, not the raw one, for numerical stability.
        Xq = (q[:L*L] + 1j * q[L*L:]).reshape(L, L)
        Q.append(q)
        basis.append(Xq)
        return True

    for h in hermitians:
        add(1j * h)
    changed = True
    while changed:
        changed = False
        current = list(basis)
        for i in range(len(current)):
            for j in range(i):
                if add(current[i] @ current[j] - current[j] @ current[i]):
                    changed = True
        if len(basis) >= L * L:
            break
    return len(basis)


def grid_2d(Nx: int, Ny: int) -> Array:
    return np.array([(2*np.pi*ix/Nx, 2*np.pi*iy/Ny) for iy in range(Ny) for ix in range(Nx)], float)


def model_I_d(k: Array) -> NDArray[np.float64]:
    x, y = k[:, 0], k[:, 1]
    t1, t2 = 1.0, 1 / np.sqrt(2)
    z = -t1 * (
        np.exp(1j*np.pi/4)
        + np.exp(1j*(x+y+np.pi/4))
        + np.exp(1j*(x-np.pi/4))
        + np.exp(1j*(y-np.pi/4))
    )
    return np.column_stack((z.real, z.imag, -2*t2*(np.cos(y)-np.cos(x))))


def model_II_d(k: Array, xi: float) -> NDArray[np.float64]:
    x, y = k[:, 0], k[:, 1]
    alpha = xi * (np.cos(x) + np.cos(y))
    return np.column_stack((-np.sin(alpha), -np.cos(alpha), np.zeros_like(alpha)))


def lower_projectors(d: NDArray[np.float64]) -> Array:
    norm = np.linalg.norm(d, axis=1)
    if np.min(norm) < 1e-12:
        raise ValueError('band touching in sampled d-vector')
    dh = d / norm[:, None]
    P = np.empty((len(d), 2, 2), dtype=np.complex128)
    for i, (x, y, z) in enumerate(dh):
        P[i] = np.array([[1-z, -x+1j*y], [-x-1j*y, 1+z]], complex) / 2
    return P


def projected_orbital_frame(P: Array, Nx: int, Ny: int) -> list[Array]:
    """Frame vectors v_{R,alpha}(k)=exp(-ikR) u_alpha(k)^*/sqrt(V), gauge-free via P.

    We obtain a band spinor from each rank-one projector.  Connectivity is gauge
    invariant, although individual frame-vector phases are not.
    """
    V = Nx * Ny
    k = grid_2d(Nx, Ny)
    spinor = np.empty((V, 2), dtype=np.complex128)
    for j in range(V):
        vals, vecs = np.linalg.eigh(P[j])
        u = vecs[:, np.argmax(vals)]
        # deterministic phase for reproducibility
        pivot = int(np.argmax(np.abs(u)))
        u *= np.exp(-1j*np.angle(u[pivot]))
        spinor[j] = u
    vectors = []
    for Ry in range(Ny):
        for Rx in range(Nx):
            phase = np.exp(-1j*(k[:, 0]*Rx + k[:, 1]*Ry)) / np.sqrt(V)
            for alpha in range(2):
                vectors.append(phase * np.conjugate(spinor[:, alpha]))
    return vectors


def audit_ghk_graphs() -> list[dict]:
    rows = []
    sizes = [(2,2),(2,3),(3,3),(3,4),(4,4),(5,5),(6,6),(7,7),(7,9),(8,8),(9,9)]
    models = [('I', None), ('II', 0.5), ('II', 1.0), ('II', 1.5), ('II', 2.0)]
    for name, xi in models:
        for Nx, Ny in sizes:
            k = grid_2d(Nx, Ny)
            d = model_I_d(k) if name == 'I' else model_II_d(k, float(xi))
            P = lower_projectors(d)
            vectors = projected_orbital_frame(P, Nx, Ny)
            comps = frame_components(vectors, tol=2e-10)
            dims = component_dimensions(vectors, comps)
            rows.append({
                'model': name if xi is None else f'II-xi{xi:g}',
                'Nx': Nx, 'Ny': Ny, 'L': Nx*Ny,
                'components': len(comps),
                'component_dims': '+'.join(map(str, dims)),
                'connected': len(comps) == 1,
            })
    return rows


def run_random_certificates() -> list[dict]:
    rng = np.random.default_rng(20260723)
    rows = []

    cases = [
        ('connected-L4', random_parseval_frame(4, 7, rng)),
        ('connected-L5', random_parseval_frame(5, 8, rng)),
        ('disconnected-2+2', disconnected_parseval_frame([2,2], 1, rng)),
        ('disconnected-2+3', disconnected_parseval_frame([2,3], 1, rng)),
    ]
    for label, vectors in cases:
        L = len(vectors[0])
        projectors = projectors_from_frame(vectors)
        frame_error = np.linalg.norm(sum(projectors) - np.eye(L))
        comps = frame_components(vectors)
        dims = component_dimensions(vectors, comps)
        lie_dim = lie_closure_dimension(projectors)
        for n in range(1, L):
            H = commutator_hamiltonian(projectors, n)
            zeros, gap = zero_count_and_gap(H)
            pred = predicted_kernel_dim(dims, n)
            rows.append({
                'case': label, 'L': L, 'n': n,
                'components': len(comps),
                'component_dims': '+'.join(map(str, dims)),
                'frame_error': frame_error,
                'lie_dimension': lie_dim,
                'uL_dimension': L*L,
                'zero_modes': zeros,
                'predicted_zero_modes': pred,
                'gap': gap,
            })
            if zeros != pred:
                raise AssertionError((label, n, zeros, pred))
        if len(comps) == 1 and lie_dim != L*L:
            raise AssertionError((label, 'Lie dimension', lie_dim, L*L))
    return rows


def main() -> None:
    random_rows = run_random_certificates()
    graph_rows = audit_ghk_graphs()

    random_csv = ROOT / 'qgn_h4_random_certificate.csv'
    with random_csv.open('w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(random_rows[0]))
        w.writeheader(); w.writerows(random_rows)

    graph_csv = ROOT / 'qgn_h4_ghk_graph_audit.csv'
    with graph_csv.open('w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(graph_rows[0]))
        w.writeheader(); w.writerows(graph_rows)

    if not all(r['connected'] for r in graph_rows):
        bad = [r for r in graph_rows if not r['connected']]
        raise AssertionError(f'disconnected GHK audit cases: {bad}')

    summary = {
        'random_certificate_rows': len(random_rows),
        'ghk_graph_cases': len(graph_rows),
        'all_ghk_audit_graphs_connected': True,
        'max_frame_error': max(float(r['frame_error']) for r in random_rows),
        'min_connected_gap': min(float(r['gap']) for r in random_rows if int(r['components']) == 1),
        'outputs': [str(random_csv), str(graph_csv)],
    }
    (ROOT / 'qgn_h4_certificate_summary.json').write_text(json.dumps(summary, indent=2))

    print('H4 random-frame certificate: PASS')
    for r in random_rows:
        print(r)
    print('\nGHK frame graph audit: PASS')
    for r in graph_rows:
        print(r)
    print('\nSUMMARY')
    print(json.dumps(summary, indent=2))


if __name__ == '__main__':
    main()
